import = ["./monokai-pro.yaml"]


env = { term = "xterm-256color" }


live_config_reload = true


[window]
# decorations = "None"
opacity = 0.97


[font]
normal = { family = "CodeNewRoman Nerd Font" }
# normal = { family = "JetbrainsMono Nerd Font" }
size = 10


[cursor]
style = { shape = "Block", blinking = "On" }
vi_mode_style = { shape = "Block", blinking = "On" }
