import = ["./catppuccin-mocha.toml"]


live_config_reload = true


[window]
# decorations = "None"
opacity = 0.97


[font]
normal = { family = "JetBrainsMono NF Light" }

size = 8


[cursor]
style = { shape = "Block", blinking = "On" }
vi_mode_style = { shape = "Block", blinking = "On" }
