import = ["./monokai-pro.yaml"]


env = { term = "xterm-256color" }


live_config_reload = true


[window]
# decorations = "None"
opacity = 0.97
dynamic_padding = true


[font]
normal = { family = "MonaspiceNe Nerd Font", style = "Light" }
italic = { family = "MonaspiceRn Nerd Font", style = "Light" }
size = 8
offset = { y = 2 }


[cursor]
style = { shape = "Block", blinking = "On" }
vi_mode_style = { shape = "Block", blinking = "On" }
